# Generated by Django 4.1.1 on 2022-09-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="date",),
    ]
